# CI de Nivel 01 - Disparo manual a partire de um clique

name: 'Execucao Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependencias
        run: yarn

      - name: Instalando Cypress
        run: yarn cypress install

      - name: Teste E2E
        run: yarn cypress run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/reports/html
